# Generated by Django 6.0.2 on 2026-02-10 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_is_important_alter_task_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-is_important', 'status', 'due_date', '-created_at']},
        ),
    ]
